Repository ND-iTC/Documents, pull requests merged in 2023-11, with the labels that each got.

#324 Minor adjustments to SFR and ECD formatting to align with stated conventions
  NDcPP_v3_0.adoc
Labels: Editorial, v3.0e

#323 TLS updates v3e
  ND_Supporting_Document_3_0.adoc
  NDcPP_v3_0.adoc
Labels: TLSWG, v3.0e

#328 Updates per NIAP PP Consistency Review
  ND_Supporting_Document_3_0.adoc
  NDcPP_v3_0.adoc
Labels: v3.0e

#331 3.0e-ver-date-change
  ND_Supporting_Document_3_0.adoc
  NDcPP_allowed_with_list.adoc
  NDcPP_v3_0.adoc
Labels: v3.0e

#330 (D)TLS RFI and issues
  ND_Supporting_Document_3_0.adoc
  NDcPP_v3_0.adoc
Labels: v3.0e

#333 v3.0 files moved to archive
  Archive/3.0/ND_Supporting_Document_3_0.adoc
  Archive/3.0/NDcPP_v3_0.adoc
  NDcPP_v3_0e.adoc
Labels: v3.0e
